version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./volumes/log/nginx/default:/var/log/nginx/default"
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    restart: always
  elasticsearch:
    build:
      context: .
      dockerfile: ./containers/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
    expose:
      - '9300'
    volumes:
      - "./volumes/elasticsearch/data:/usr/share/elasticsearch/data"
  kibana:
    build:
      context: .
      dockerfile: ./containers/kibana/Dockerfile
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  logstash:
    build:
      context: .
      dockerfile: ./containers/logstash/Dockerfile
    ports:
      # Beats input -- https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-beats.html
      - '5044:5044'
      # UDP input -- https://www.elastic.co/guide/en/logstash/master/plugins-inputs-udp.html#plugins-inputs-udp-codec
      - '43448:43448/udp'
      # Monitoring APIs -- https://www.elastic.co/guide/en/logstash/5.0/monitoring.html
      - '9600:9600'
    volumes:
      - "./volumes/log/nginx/default:/var/log/nginx/default"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
